import Head from 'next/head';
import { Container } from '@/components/shared/Container';
import HeroDescription from '@/components/home/HeroDescription';
import Skills from '@/components/home/Skills';
import Experience from '@/components/home/Experience';
import Projects from '@/components/home/Projects';
import Footer from '@/components/shared/Footer';
import Header from '@/components/shared/Header';
import Education from '@/components/home/Education';
import Achievement from '@/components/home/Achievement';
import ContactCard from '@/components/home/ContactCard';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <HeroDescription />
        <Skills />
        <Experience />
        <Projects />
        <Education />
        <Achievement />
        <ContactCard />
        <Footer />
      </Container>
    </>
  );
}
