import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Container } from '@/components/shared/Container';
import HeroDescription from '@/components/home/HeroDescription';
import Skills from '@/components/home/Skills';
import Experience from '@/components/home/Experience';
import Projects from '@/components/home/Projects';
import Footer from '@/components/shared/Footer';
import Header from '@/components/shared/Header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header />
        <HeroDescription />
        {/* <div className="w-full mt-20 flex flex-row justify-between items-center">
          <HeroDescription />
          <Card
            name="Sambit Sankalp"
            title="Full Stack Devloper"
            social={{ github: '/', dribbble: '/', twitter: '/', email: '/' }}
          />
        </div> */}
        <Skills />
        <Experience />
        <Projects />
        <Footer />
      </Container>
    </>
  );
}
